language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: true

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "ETR0GRqjEv6OAGGpr0eNQ2mCdPFLVV4ppmU6cDbGdHyfr1a/SVA2Do75gDx/qwjf9FAXb0qNPypCU7CIJ6L+U2yVpn65qbAZ5fgKLk2xA8xjkfrn2W5Fcif7kxusvqJyYXmq1mhIBkZdNQjwfJPsSO5zZjGUeqv/cBUz5lvfa/I="
    - GIT_COMMITTER_NAME=akagane99
    - GIT_COMMITTER_EMAIL=akagane99@gmail.com
    - GIT_AUTHOR_NAME=akagane99
    - GIT_AUTHOR_EMAIL=akagane99@gmail.com

addons:
  apt:
    packages:
    - libav-tools
    - libavcodec-extra

before_script:
  - sudo ln -s /usr/bin/avconv /usr/bin/ffmpeg
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - . tools/build/plugins/cakephp/travis/pre.sh

script:
  - travis_wait . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
